id: P009474
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-19 19:40:28.452183
source_metadata:
  id: bdr:W1KG975
  title: ཚོགས་གསུམ་གྱི་རྣམ་བཤད་དཔྱིད་ཀྱི་མྱུ་གུ་
  author: ''
  volumes:
    7970ae2fe9a24b20b0ad8dcfd18329ef:
      image_group_id: I1KG1123
      title: ''
      volume_number: 1
      total_pages: 184
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
