id: P009474
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG975
  title: ཚོགས་གསུམ་གྱི་རྣམ་བཤད་དཔྱིད་ཀྱི་མྱུ་གུ་
  author: ''
  volumes:
    7970ae2fe9a24b20b0ad8dcfd18329ef:
      image_group_id: I1KG1123
      title: ''
      volume_number: 1
      total_pages: 184
